#ifndef __CAPACITIES_HPP__
#define __CAPACITIES_HPP__

// ValuesBank
#define CAPACITY_CONSTDOUBLES 2048

// Trex
#define CAPACITY_TREXDELAY_BUFFERSIZE 44100

// JurassicVoice
//#define CAPACITY_JURASSICVOICE_PARAMS 2
#define CAPACITY_JURASSICSYNTHELEMENT_TREX 32
#define CAPACITY_JURASSICSYNTHELEMENT_PRETREX 32

// Synthesizer
#define CAPACITY_INPUTS_PER_EFFECT 128
#define CAPACITY_EFFECTS_PER_INSTRUMENT 16
#define CAPACITY_EFFECTS_PER_SYNTHESIZER CAPACITY_EFFECTS_PER_INSTRUMENT
#define CAPACITY_EFFECTINPUTS_PER_PLAYINGVOICE CAPACITY_EFFECTS_PER_INSTRUMENT
#define CAPACITY_VOICES_PER_INSTRUMENT 32
#define CAPACITY_PLAYINGVOICES_PER_SYNTHESIZER 128
#define CAPACITY_OUTPUTS_PER_SYNTHESIZER 256

// Egg threads
#define EGG_REPEAT_MINTHREADS 4
#define EGG_FOREVER_THREADS 16
#define EGG_MELINJECT_THREADS 3

#endif